# agents/base_agent.py

from abc import ABC, abstractmethod

class BaseAgent(ABC):
    def __init__(self, name: str, llm):
        """
        Initialize the base agent.

        Args:
            name (str): Name of the agent.
            llm: Instance of the language model used by the agent.
        """
        self.name = name
        self.llm = llm

    @abstractmethod
    def generate_response(self, *args, **kwargs):
        """
        Abstract method to generate a response based on input data.

        Returns:
            Any: Response generated by the agent.
        """
        pass
